name: Create Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          architecture: x64
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.13
      - name: Setup workspace
        run: gradle preprocessBase
      - name: Build
        run: gradle collectBuilds -Prelease=true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LoTAS-Light-Builds
          path: build/*.jar
          if-no-files-found: error
      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: 'build/!(-@(dev|sources|javadoc|all)).jar'

  publish:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.20.4", "1.20.6", "1.21.1", "1.21.3", "1.21.4", "1.21.5", "1.21.8"]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: build/
          merge-multiple: true
      - name: Publish ${{ matrix.version }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: 'build/*-${{ matrix.version }}-*!(*-@(dev|sources|javadoc|all)).jar'
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
